name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  GITHUB_PACKAGES_ACCESS_USER: ${{ secrets.GH_PACKAGES_ACCESS_USER }}
  GITHUB_PACKAGES_ACCESS_TOKEN: ${{ secrets.GH_PACKAGES_ACCESS_TOKEN }}

jobs:
  build:
    name: Build on Java ${{ matrix.java-version }}

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up JDK with Dependency Caching
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 8
          cache: 'gradle'

      - name: Build and test
        run: ./gradlew --continue check
